services:
  postgres:
    ports:
      - "5432:5432"

  springboot:
    ports:
      - "8080:8080"

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./front:/front
      - /front/node_modules
    depends_on:
      - springboot
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    depends_on:
      - front
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - app-network
